syntax = "proto3";

package order.v1;

option go_package = "github.com/pinnakarn-k/commerce-core-go/internal/gen/order/v1;orderv1";

service OrderQueryService {
  rpc GetOrderDetail(GetOrderDetailRequest) returns (OrderDetailResponse);
}

message GetOrderDetailRequest {
  int64 user_id = 1;
  int64 order_id = 2;
}

message OrderDetailResponse {
  Order order = 1;
  repeated OrderItem items = 2;
}

message Order {
  int64 id = 1;
  int64 user_id = 2;
  string idempotency_key = 3;
  string status = 4;
  int32 total_amount = 5;
  string currency = 6;
  string created_at = 7;
  string updated_at = 8;
  optional string paid_at = 9;
  optional string cancelled_at = 10;
}

message OrderItem {
  int64 id = 1;
  int64 order_id = 2;
  int64 product_id = 3;
  string product_name = 4;
  string product_sku = 5;
  int32 quantity = 6;
  int32 unit_price_amount = 7;
  int32 line_total_amount = 8;
  string currency = 9;
  string created_at = 10;
}